# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
    - NOT_CRAN=true

after_success:
  - Rscript -e 'covr::codecov()'